### ISSUE TITLE
0.12.0: from sksurv.ensemble import RandomSurvivalForest fails

### ISSUE THREAD

**Issue by gregchu** [sebp/scikit-survival#107]
Upon upgrading to 0.12.0

```
>>> from sksurv.ensemble import RandomSurvivalForest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gchu/miniconda3/envs/dev/lib/python3.6/site-packages/sksurv/ensemble/__init__.py", line 2, in <module>
    from .forest import RandomSurvivalForest  # noqa: F401
  File "/Users/gchu/miniconda3/envs/dev/lib/python3.6/site-packages/sksurv/ensemble/forest.py", line 14, in <module>
    from ..tree import SurvivalTree
  File "/Users/gchu/miniconda3/envs/dev/lib/python3.6/site-packages/sksurv/tree/__init__.py", line 1, in <module>
    from .tree import SurvivalTree  # noqa: F401
  File "/Users/gchu/miniconda3/envs/dev/lib/python3.6/site-packages/sksurv/tree/tree.py", line 14, in <module>
    from ._criterion import LogrankCriterion
  File "_splitter.pxd", line 34, in init sksurv.tree._criterion
ValueError: sklearn.tree._splitter.Splitter size changed, may indicate binary incompatibility. Expected 368 from C header, got 360 from PyObject
>>>
```

**Comment by gregchu** [comment]
Actually, in 0.11.0, its a warning (instead of an error)
```
>>> from sksurv.ensemble import RandomSurvivalForest
/Users/gchu/miniconda3/envs/dev/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: sklearn.tree._splitter.Splitter size changed, may indicate binary incompatibility. Expected 360 from C header, got 368 from PyObject
  return f(*args, **kwds)
>>>
```

**Comment by sebp** [comment]
Seems like the wrong scikit-learn version is installed. It should be 
0.22. Did you install from source or via conda?

**Comment by gregchu** [comment]
Ah I see, I was installing via pip

So now I'm trying a couple paths
1) installing via `conda install -c sebp scikit-survival`
Results in 
```
Downloading and Extracting Packages
scikit-survival-0.12 | 1007 KB   | ################################################################################################################# | 100%

ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/sebp/osx-64/scikit-survival-0.12.0-py36h86efe34_0.tar.bz2'.
  download saved to: /Users/gchu/miniconda3/pkgs/scikit-survival-0.12.0-py36h86efe34_0.tar.bz2
  expected md5: 4263054ca83fbf98f423b9d3e6a6759e
  actual md5: ce4fff9496ae46b960f882a2143cb0e9
```

and 2) installing via
```
python ci/list-requirements.py requirements/dev.txt > /tmp/requirements.txt
conda create -n sksurv -c sebp python=3 --file /tmp/requirements.txt
```
Installs successfully, but when importing
```
Python 3.8.2 (default, Mar 26 2020, 10:43:30)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sksurv.ensemble import RandomSurvivalForest
^[[OTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gchu/dev/deps/scikit-survival/sksurv/ensemble/__init__.py", line 1, in <module>
    from .boosting import ComponentwiseGradientBoostingSurvivalAnalysis, GradientBoostingSurvivalAnalysis  # noqa: F401
  File "/Users/gchu/dev/deps/scikit-survival/sksurv/ensemble/boosting.py", line 32, in <module>
    from .survival_loss import LOSS_FUNCTIONS, CensoredSquaredLoss, \
  File "/Users/gchu/dev/deps/scikit-survival/sksurv/ensemble/survival_loss.py", line 21, in <module>
    from ._coxph_loss import coxph_loss, coxph_negative_gradient
ModuleNotFoundError: No module named 'sksurv.ensemble._coxph_loss'
>>>
```

**Comment by sebp** [comment]
For some reason, there are two packages with identical names for OSX on 
anaconda.org. I'll investigate.

**Comment by gregchu** [comment]
Thank you, @sebp!

**Comment by sebp** [comment]
I uploaded a new package, can you please try now.

**Comment by gregchu** [comment]
works! thanks

**Comment by JeffreyEnglish** [comment]
I came across the same issue as @gregchu installing from pip. My guess is that the same problem that happened on anaconda.org is happening on PyPi as well.

**Comment by gregchu** [comment]
@JeffreyEnglish what's the exact error you're seeing?

Seb fixed the anaconda distribution. I was able to install via PyPi, you just need to ensure that the dependency versions are correct. For me, what Seb called out about scikit-learn's version not being 0.22 fixed the issue.

**Comment by sebp** [comment]
Can you please post a detailed description of what you are trying to do 
and what error you are getting, please. I just installed it via pip, and 
all unit tests passed.

**Comment by JeffreyEnglish** [comment]
Hi Greg & Seb, thanks for the quick replies.

Here's the error I'm getting:

```
>>> from sksurv.ensemble import SurvivalRandomForest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jenglish\AppData\Local\Programs\Python\Python37\lib\site-packages\sksurv\ensemble\__init__.py", line 2, in <module>
    from .forest import RandomSurvivalForest  # noqa: F401
  File "C:\Users\jenglish\AppData\Local\Programs\Python\Python37\lib\site-packages\sksurv\ensemble\forest.py", line 14, in <module>
    from ..tree import SurvivalTree
  File "C:\Users\jenglish\AppData\Local\Programs\Python\Python37\lib\site-packages\sksurv\tree\__init__.py", line 1, in <module>
    from .tree import SurvivalTree  # noqa: F401
  File "C:\Users\jenglish\AppData\Local\Programs\Python\Python37\lib\site-packages\sksurv\tree\tree.py", line 14, in <module>
    from ._criterion import LogrankCriterion
  File "_splitter.pxd", line 34, in init sksurv.tree._criterion
ValueError: sklearn.tree._splitter.Splitter size changed, may indicate binary incompatibility. Expected 368 from C header, got 360 from PyObject
```

Checking the scikit-learn version:
```
 >>> sklearn.__version__
'0.22.2.post1'
```

**Comment by sebp** [comment]
That's odd. Did you install all dependencies via pip?

You can also try installing the pre-built wheel, maybe it helps:

https://ci.appveyor.com/api/buildjobs/709qal4kkvsudaae/artifacts/dist%2Fscikit_survival-0.12.0-cp37-cp37m-win_amd64.whl

**Comment by JeffreyEnglish** [comment]
I had installed the dependencies via pip. Many of them were already installed so it's possible a version conflict occurred somewhere.

I tried the pre-built wheel and it works! Thank you for the help.
