### ISSUE TITLE
Cannot pip install scikit-survival 0.13

### ISSUE THREAD

**Issue by alexandrehuat** [sebp/scikit-survival#130]
**Describe the bug**

In a Python 3.7 virtual environment on macOS 10.15.5, the installation of scikit-survival version 0.13 and 0.13.1 fails with `pip`. Version 0.12 is successfully installed however. Here is the command line output when it fails:

```bash
alexandrehuat@Alexandre-Huats-MacBook-Air: ~/Documents/Professionnel/Doctorat/Devel/my-phd master ⚡
$ pip install -vU scikit-survival==0.13                                                                                                                          [11:02:19]
Non-user install because user site-packages disabled
Created temporary directory: /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-ephem-wheel-cache-lun68u7s
Created temporary directory: /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-req-tracker-e676mr_3
Initialized build tracking at /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-req-tracker-e676mr_3
Created build tracker: /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-req-tracker-e676mr_3
Entered build tracker: /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-req-tracker-e676mr_3
Created temporary directory: /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-install-0topv6dg
1 location(s) to search for versions of scikit-survival:
* https://pypi.org/simple/scikit-survival/
Fetching project page and analyzing links: https://pypi.org/simple/scikit-survival/
Getting page https://pypi.org/simple/scikit-survival/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
Getting credentials from keyring for pypi.org
Looking up "https://pypi.org/simple/scikit-survival/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/scikit-survival/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/a1/d1/b25a794cdd257b9c2ef2c080334567fa032900c15bed590c5b6003c7fd83/scikit-survival-0.1.tar.gz#sha256=1cd37604907007e5ed0efa3892a8cde2f11076440cb60e6798c22412a111775d (from https://pypi.org/simple/scikit-survival/), version: 0.1
  Found link https://files.pythonhosted.org/packages/2d/63/3a23b79990c26fc28a4431c816dd1ac518f87f063af5e1af46d0bb58475e/scikit-survival-0.2.tar.gz#sha256=e4c0120e3ef6f26ae746efa8b31a77c640803919a69e0b9cdf82da24b13f178f (from https://pypi.org/simple/scikit-survival/), version: 0.2
  Found link https://files.pythonhosted.org/packages/2c/d3/3e6d59a73efb5a21a81fede3a100809dd8019fe6889e61583b73d9243d78/scikit-survival-0.3.tar.gz#sha256=20d8cf2df4b55276600b4fa188424b4e415f9834a58609fac7cdb277ce9ad8f8 (from https://pypi.org/simple/scikit-survival/), version: 0.3
  Found link https://files.pythonhosted.org/packages/cd/f6/8cca16b35a4cfd7924bd962696348c871591680292292e80f5168e6fb0ec/scikit-survival-0.4.tar.gz#sha256=2cfde396f38b65aadb077a543ae3ea198056220325c157076a20069797b336ad (from https://pypi.org/simple/scikit-survival/), version: 0.4
  Found link https://files.pythonhosted.org/packages/8b/89/1283a03de5a0d46e7f80dfa40f30b8799aaa2f3d695b05662468387c04d4/scikit-survival-0.5.tar.gz#sha256=30686ccf57ba9116a0788e15a784193fbde31e0bb0ccb98716f189bba7289d48 (from https://pypi.org/simple/scikit-survival/), version: 0.5
  Found link https://files.pythonhosted.org/packages/db/79/db3eec665bebc8167ace14427b5b91436863483c91bd957af6358fe75488/scikit-survival-0.6.0.tar.gz#sha256=8af8ad74b757c136f0a13983e759ef89b3c2442b0e8611bbf14263c8c9bf9dab (from https://pypi.org/simple/scikit-survival/), version: 0.6.0
  Found link https://files.pythonhosted.org/packages/44/40/c2edb93198a678d5db7a76e45e0fc08543ef4e66303a0926291a6ddc2cc7/scikit-survival-0.7.tar.gz#sha256=2f050fedef9beae1d7e57f43905931a8a97101bf4ad7f404d8c7ac4fc22a580f (from https://pypi.org/simple/scikit-survival/), version: 0.7
  Found link https://files.pythonhosted.org/packages/36/12/51780840093d9124d273665cea73ac9e297e5a9931304ed6add0083ebcda/scikit-survival-0.8.tar.gz#sha256=456983190a1054615e2efd5e7aeeec4a06da009c94d71ebe6f6f769b30c87c6f (from https://pypi.org/simple/scikit-survival/), version: 0.8
  Found link https://files.pythonhosted.org/packages/82/ad/af8dd2cd8138933be97f022737461876f5a2d1d2660ce423f80ea902e589/scikit-survival-0.9.tar.gz#sha256=e707cea07cac3ab33811fa8db74f3729c9e9bde59654db98c871560c5e73e095 (from https://pypi.org/simple/scikit-survival/), version: 0.9
  Found link https://files.pythonhosted.org/packages/ee/12/0f7741658971c43fd63895ec70a775fd609710384409440ef03e786df870/scikit-survival-0.10.tar.gz#sha256=ade8e5ba6494bd02762d6d99d9767f11f8dafa4cefb05d1289edda4e116cdafc (from https://pypi.org/simple/scikit-survival/), version: 0.10
  Found link https://files.pythonhosted.org/packages/4d/dc/866c223cd09533ea18c7e716df851e76511bd1ce5f4f1d2d0e5ce3d1c1b7/scikit-survival-0.11.tar.gz#sha256=25c8e3d121caf05f602174dbc8d2b552310ec27c0c22f3fbd7717b99b18b8760 (from https://pypi.org/simple/scikit-survival/) (requires-python:>=3.5), version: 0.11
  Found link https://files.pythonhosted.org/packages/5a/04/f8b7f3ad96c234f853b03292ba73e1a9cc0526ebb087ffb00336fd13e9d3/scikit-survival-0.12.0.tar.gz#sha256=130024122f95676be8e589c76608f5c8c35a83028b980a540549e9b1134a203c (from https://pypi.org/simple/scikit-survival/) (requires-python:>=3.5), version: 0.12.0
  Found link https://files.pythonhosted.org/packages/00/97/9b167694a15acf11c8f0baf595572cb86c5feb5e5524c3b2b05937a5f901/scikit-survival-0.13.0.tar.gz#sha256=9472cb27f4fcdccc67ce05324b4308b19ce237ca99c4ccfa53e89c09392bf78d (from https://pypi.org/simple/scikit-survival/) (requires-python:>=3.5), version: 0.13.0
  Found link https://files.pythonhosted.org/packages/60/8a/46782be432e93ce74af46b8e8ee4be74df6edfb86c619742fa4265a7c69a/scikit-survival-0.13.1.tar.gz#sha256=0f2da3b0dfdcaa11cce93746fdeb7cfe342cd656fbc490a7b07abbc2e6ee63eb (from https://pypi.org/simple/scikit-survival/) (requires-python:>=3.5), version: 0.13.1
Given no hashes to check 1 links for project 'scikit-survival': discarding no candidates
Using version 0.13.0 (newest of versions: 0.13.0)
Collecting scikit-survival==0.13
  Created temporary directory: /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-unpack-4vs8tdsr
  Getting credentials from keyring for files.pythonhosted.org
  Looking up "https://files.pythonhosted.org/packages/00/97/9b167694a15acf11c8f0baf595572cb86c5feb5e5524c3b2b05937a5f901/scikit-survival-0.13.0.tar.gz" in the cache
  Current age based on date: 406
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 406
  Using cached scikit-survival-0.13.0.tar.gz (1.8 MB)
  Added scikit-survival==0.13 from https://files.pythonhosted.org/packages/00/97/9b167694a15acf11c8f0baf595572cb86c5feb5e5524c3b2b05937a5f901/scikit-survival-0.13.0.tar.gz#sha256=9472cb27f4fcdccc67ce05324b4308b19ce237ca99c4ccfa53e89c09392bf78d to build tracker '/private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-req-tracker-e676mr_3'
  Created temporary directory: /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-build-env-60sgo_6j
  Running command /Users/alexandrehuat/.virtualenvs/my-phd/bin/python /Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-build-env-60sgo_6j/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'setuptools_scm[toml]>=3.4' 'Cython>=0.29.16' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'scikit-learn>=0.22.0,<0.24.0'
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  Installing build dependencies ... error
ERROR: Command errored out with exit status 1: /Users/alexandrehuat/.virtualenvs/my-phd/bin/python /Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-build-env-60sgo_6j/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'setuptools_scm[toml]>=3.4' 'Cython>=0.29.16' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'scikit-learn>=0.22.0,<0.24.0' Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 333, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 488, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 68, in _setup_isolation
    "Installing build dependencies"
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/build_env.py", line 199, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /Users/alexandrehuat/.virtualenvs/my-phd/bin/python /Users/alexandrehuat/.virtualenvs/my-phd/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-build-env-60sgo_6j/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'setuptools_scm[toml]>=3.4' 'Cython>=0.29.16' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'scikit-learn>=0.22.0,<0.24.0' Check the logs for full command output.
Removed scikit-survival==0.13 from https://files.pythonhosted.org/packages/00/97/9b167694a15acf11c8f0baf595572cb86c5feb5e5524c3b2b05937a5f901/scikit-survival-0.13.0.tar.gz#sha256=9472cb27f4fcdccc67ce05324b4308b19ce237ca99c4ccfa53e89c09392bf78d from build tracker '/private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-req-tracker-e676mr_3'
Removed build tracker: '/private/var/folders/q0/8v4w2wjs7ws2nxw4h3h1p8680000gn/T/pip-req-tracker-e676mr_3'
FAIL: 1
```

**Versions**
Please execute the following snippet and paste the output below.

```python
import sklearn; sklearn.show_versions()
import sksurv; print("sksurv:", sksurv.__version__)
import cvxopt; print("cvxopt:", cvxopt.__version__)
import cvxpy; print("cvxpy:", cvxpy.__version__)
import numexpr; print("numexpr:", numexpr.__version__)
import osqp; print("osqp:", osqp.OSQP().version())
```

```text
System:
    python: 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)  [Clang 6.0 (clang-600.0.57)]
executable: /Users/alexandrehuat/.virtualenvs/my-phd/bin/python
   machine: Darwin-19.5.0-x86_64-i386-64bit

Python dependencies:
       pip: 20.1.1
setuptools: 46.0.0
   sklearn: 0.22.2.post1
     numpy: 1.18.1
     scipy: 1.4.1
    Cython: 0.29.15
    pandas: 1.0.3
matplotlib: 3.2.1
    joblib: 0.14.1

Built with OpenMP: True
sksurv: 0.12.0
cvxopt: 1.2.4
cvxpy: 1.0.25
numexpr: 2.7.1
osqp: 0.5.0
```

**Comment by sebp** [comment]
It seems you have typing installed, which you don't need, because it is part of the standard library in python 3.7, see python/typing#573

**Comment by alexandrehuat** [comment]
That was an easy fix. Thank you.

```bash
pip uninstall typing
pip install -U scikit-survival
```
