### ISSUE TITLE
CoxPHSurvivalAnalysis.predict_cumulative_hazard_function throws an AttributeError

### ISSUE THREAD

**Issue by ChemGuy88** [sebp/scikit-survival#148]
**The Bug**
`CoxPHSurvivalAnalysis.predict_cumulative_hazard_function` throws an `AttributeError`.

**My code**
```python
# The data is from https://rdrr.io/cran/epitools/man/wcgs.html
exposure3 = data[['Height0', 'Weight0', 'Sbp0', 'Chol0', 'Dibpat0']]
validValues = np.argwhere(data['Chol0'].to_numpy() != '.')[:,0]
exposure3 = exposure3.iloc[validValues]
data_y3 = data_y[validValues]

dtypes = {'Height0': 'int64',
          'Weight0': 'int64',
          'Sbp0': 'int64',
          'Chol0': 'int64',
          'Dibpat0': 'category'}
exposure3 = exposure3.astype(dtypes)

model = CoxPHSurvivalAnalysis().fit(exposure3, data_y3)
chf_funcs = model.predict_cumulative_hazard_function(exposure3[:5])
```

**Expected Results**
I expect an output, the Cum. Haz. Funcs.

**Actual Results**
```python
AttributeError: 'float' object has no attribute 'exp'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/Users/herman/Documents/epistats/hw/hw4/hw4p2.py", line 125, in <module>
    chf_funcs = model.predict_cumulative_hazard_function(exposure3[:5])

  File "/opt/anaconda3/lib/python3.8/site-packages/sksurv/linear_model/coxph.py", line 527, in predict_cumulative_hazard_function
    return self._baseline_model.get_cumulative_hazard_function(self.predict(X))

  File "/opt/anaconda3/lib/python3.8/site-packages/sksurv/linear_model/coxph.py", line 97, in get_cumulative_hazard_function
    risk_score = numpy.exp(linear_predictor)

TypeError: loop of ufunc does not support argument 0 of type float which has no callable exp method
```

**Versions**
I'm running this on various machines.

```python
# Home machine

System:
    python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)  [Clang 6.0 (clang-600.0.57)]
executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
   machine: Darwin-20.1.0-x86_64-i386-64bit

Python dependencies:
       pip: 20.2.4
setuptools: 40.8.0
   sklearn: 0.22.1
     numpy: 1.19.1
     scipy: 1.5.2
    Cython: 0.29.15
    pandas: 1.1.2
matplotlib: 3.1.1
    joblib: 0.14.1

Built with OpenMP: True
sksurv: 0.13.1
cvxopt: 1.2.5
cvxpy: 1.1.5
numexpr: 2.7.1
osqp: 0.5.0

# Work machine
```

**Comment by sebp** [comment]
The error is due to Dibpat0 being of category dtype, in which case 
np.asarray(exposure3[:5]) results in a array with dtype=object.

It works for fit, because sklearn's check_array seems to be aware of 
pandas dtypes, whereas np.asarray is not. Therefore, we should use 
check_array during prediction too.

**Comment by ChemGuy88** [comment]
Hi, I ran my script again and it worked. I have just recently reinstalled scikit-survival, so maybe it already included your commit.

```python
System:
    python: 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)  [Clang 6.0 (clang-600.0.57)]
executable: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 20.2.4
   setuptools: 41.2.0
      sklearn: 0.23.2
        numpy: 1.19.4
        scipy: 1.5.4
       Cython: None
       pandas: 1.1.4
   matplotlib: 3.3.3
       joblib: 0.17.0
threadpoolctl: 2.1.0

Built with OpenMP: True
sksurv: 0.14.0
cvxopt: 1.2.5
cvxpy: 1.1.7
numexpr: 2.7.1
osqp: 0.5.0
```
