### ISSUE TITLE
pip install fails: "Getting requirements to build wheel did not run successfully"

### ISSUE THREAD

**Issue by alexandrehuat** [sebp/scikit-survival#333]
### Describe the Bug

I have a Docker container (python:3 image) in which I want to install scikit-survival. When I arrive at the `pip install scikit-survival` step, it fails. Fyi, the CMake dependency is installed. No bug happens when I run the same commands in the host Ubuntu machine. It fails with several versions of scikit-survival. The full error message is:

```bash
Collecting scikit-survival
  Downloading scikit-survival-0.19.0.post1.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 44.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  free(self.riskset_left)
      
          def __reduce__(self):
              return (type(self), (self.n_outputs, self.n_samples, self.event_times), self.__getstate__())
      
          cdef int init(self, const DOUBLE_t[:, ::1] y, DOUBLE_t* sample_weight,
              ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:131:9: Signature not compatible with previous declaration
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          # The criterion object is maintained such that left and right collected
          # statistics correspond to samples[start:pos] and samples[pos:end].
      
          # Methods
          cdef int init(
                      ^
      ------------------------------------------------------------
      
      /tmp/pip-build-env-hx4f4n_a/overlay/lib/python3.11/site-packages/sklearn/tree/_criterion.pxd:44:17: Previous declaration is here
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Riskset * riskset_total
          cdef Riskset * riskset_left
      
          def __cinit__(self, SIZE_t n_outputs, SIZE_t n_samples, const DOUBLE_t[::1] event_times):
              # Default values
              self.sample_weight = NULL
                                  ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:102:29: Cannot convert 'void *' to memoryviewslice
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                        SIZE_t end) nogil except -1:
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
                                  ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:138:29: Cannot convert 'DOUBLE_t *' to memoryviewslice
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.pos = self.end
              return 0
      
          cdef int update(self, SIZE_t new_pos) nogil except -1:
              """Updated statistics by moving samples[pos:new_pos] to the left."""
              cdef const double* sample_weight = self.sample_weight
                                                    ^
      ------------------------------------------------------------
      
      sksurv/tree/_criterion.pyx:209:47: Cannot assign type 'const DOUBLE_t[:]' to 'const double *'
      Compiling sksurv/bintrees/_binarytrees.pyx because it changed.
      Compiling sksurv/kernels/_clinical_kernel.pyx because it changed.
      Compiling sksurv/ensemble/_coxph_loss.pyx because it changed.
      Compiling sksurv/svm/_prsvm.pyx because it changed.
      Compiling sksurv/svm/_minlip.pyx because it changed.
      Compiling sksurv/tree/_criterion.pyx because it changed.
      Compiling sksurv/linear_model/_coxnet.pyx because it changed.
      [1/7] Cythonizing sksurv/bintrees/_binarytrees.pyx
      [2/7] Cythonizing sksurv/ensemble/_coxph_loss.pyx
      [3/7] Cythonizing sksurv/kernels/_clinical_kernel.pyx
      [4/7] Cythonizing sksurv/linear_model/_coxnet.pyx
      [5/7] Cythonizing sksurv/svm/_minlip.pyx
      [6/7] Cythonizing sksurv/svm/_prsvm.pyx
      [7/7] Cythonizing sksurv/tree/_criterion.pyx
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hx4f4n_a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-hx4f4n_a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-hx4f4n_a/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 222, in <module>
        File "<string>", line 195, in setup_package
        File "<string>", line 175, in get_extensions
        File "<string>", line 139, in cythonize_extensions
        File "/tmp/pip-build-env-hx4f4n_a/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-hx4f4n_a/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: sksurv/tree/_criterion.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

### Code Sample to Reproduce the Bug

My Dockerfile is:

```bash
FROM python:3
RUN python3 -m pip install -U pip setuptools wheel
RUN apt-get update -y && apt-get install -y cmake
RUN pip install scikit-survival
```

I'm running out of ideas of why this happens. Thank you for your help.

**Comment by alexandrehuat** [comment]
I fixed the problem by changing **Python version to 3.10**. So I simplified my Dockerfile to:
```bash
FROM python:3.10
ADD ./requirements.txt /pyrequirements.txt
RUN python3 -m pip install -U pip && pip install setuptools wheel
RUN pip install -r /pyrequirements.txt
```
(CMake is already installed apparently.)

I don't know exactly why but it looks like bindings with Cython in Python 3.11 don't work fine for sksurv.

**Comment by sebp** [comment]
I haven't tested it with Python 3.11. It's likely that it requires updates of sksurv itself or its dependencies (e.g. scikit-learn, Cython).
