### ISSUE TITLE
Unable to install the library for Windows10 Python3.11.1

### ISSUE THREAD

**Issue by Ligadata-YazeedHasan** [sebp/scikit-survival#336]
**Describe the bug**

I have been trying to install the library on Windows10 with Python3.11.1 and pip 22.3.1

However, the installation had errors and didn't complete. 

error: subprocess-exited-with-error

**Code Sample to Reproduce the Bug**
`pip install scikit-survival`

**Expected Results**
The installation should be successful and finish without any issue 

**Actual Results**

```python
$ pip install scikit-survival
Collecting scikit-survival
  Using cached scikit-survival-0.19.0.post1.tar.gz (2.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  free(self.riskset_left)

          def __reduce__(self):
              return (type(self), (self.n_outputs, self.n_samples, self.event_ti
mes), self.__getstate__())

          cdef int init(self, const DOUBLE_t[:, ::1] y, DOUBLE_t* sample_weight,
              ^
      ------------------------------------------------------------

      sksurv\tree\_criterion.pyx:131:9: Signature not compatible with previous d
eclaration

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

          # The criterion object is maintained such that left and right collecte
d
          # statistics correspond to samples[start:pos] and samples[pos:end].

          # Methods
          cdef int init(
                      ^
      ------------------------------------------------------------

      C:\Users\User\AppData\Local\Temp\pip-build-env-h0wsz9mp\overlay\Lib\site-p
ackages\sklearn\tree\_criterion.pxd:44:17: Previous declaration is here

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Riskset * riskset_total
          cdef Riskset * riskset_left

          def __cinit__(self, SIZE_t n_outputs, SIZE_t n_samples, const DOUBLE_t
[::1] event_times):
              # Default values
              self.sample_weight = NULL
                                  ^
      ------------------------------------------------------------

      sksurv\tree\_criterion.pyx:102:29: Cannot convert 'void *' to memoryviewsl
ice

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                        SIZE_t end) nogil except -1:
              """Initialize the criterion at node samples[start:end] and
                 children samples[start:start] and samples[start:end]."""
              # Initialize fields
              self.y = y
              self.sample_weight = sample_weight
                                  ^
      ------------------------------------------------------------

      sksurv\tree\_criterion.pyx:138:29: Cannot convert 'DOUBLE_t *' to memoryvi
ewslice

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.pos = self.end
              return 0

          cdef int update(self, SIZE_t new_pos) nogil except -1:
              """Updated statistics by moving samples[pos:new_pos] to the left."
""
              cdef const double* sample_weight = self.sample_weight
                                                    ^
      ------------------------------------------------------------

      sksurv\tree\_criterion.pyx:209:47: Cannot assign type 'const DOUBLE_t[:]'
to 'const double *'
      Compiling sksurv/bintrees/_binarytrees.pyx because it changed.
      Compiling sksurv/kernels/_clinical_kernel.pyx because it changed.
      Compiling sksurv/ensemble/_coxph_loss.pyx because it changed.
      Compiling sksurv/svm/_prsvm.pyx because it changed.
      Compiling sksurv/svm/_minlip.pyx because it changed.
      Compiling sksurv/tree/_criterion.pyx because it changed.
      Compiling sksurv/linear_model/_coxnet.pyx because it changed.
      [1/7] Cythonizing sksurv/bintrees/_binarytrees.pyx
      [2/7] Cythonizing sksurv/ensemble/_coxph_loss.pyx
      [3/7] Cythonizing sksurv/kernels/_clinical_kernel.pyx
      [4/7] Cythonizing sksurv/linear_model/_coxnet.pyx
      [5/7] Cythonizing sksurv/svm/_minlip.pyx
      [6/7] Cythonizing sksurv/svm/_prsvm.pyx
      [7/7] Cythonizing sksurv/tree/_criterion.pyx
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-pac
kages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-pac
kages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-pac
kages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_f
or_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-h0wsz9mp\overlay\Li
b\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_w
heel
          return self._get_build_requires(config_settings, requirements=['wheel'
])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-h0wsz9mp\overlay\Li
b\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-h0wsz9mp\overlay\Li
b\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 222, in <module>
        File "<string>", line 195, in setup_package
        File "<string>", line 175, in get_extensions
        File "<string>", line 139, in cythonize_extensions
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-h0wsz9mp\overlay\Li
b\site-packages\Cython\Build\Dependencies.py", line 1112, in cythonize
          cythonize_one(*args)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-h0wsz9mp\overlay\Li
b\site-packages\Cython\Build\Dependencies.py", line 1235, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: sksurv/tree/_criterion.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with
pip.

```

**Versions**
Please execute the following snippet and paste the output below.

```python
import sklearn; sklearn.show_versions()
import sksurv; print("sksurv:", sksurv.__version__)
import cvxopt; print("cvxopt:", cvxopt.__version__)
import cvxpy; print("cvxpy:", cvxpy.__version__)
import numexpr; print("numexpr:", numexpr.__version__)
import osqp; print("osqp:", osqp.OSQP().version())
```

```
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn; sklearn.show_versions()

System:
    python: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
executable: C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
      sklearn: 1.2.0
          pip: 22.3.1
   setuptools: 65.5.0
        numpy: 1.24.1
        scipy: 1.10.0
       Cython: None
       pandas: 1.5.2
   matplotlib: 3.6.3
       joblib: 1.2.0
threadpoolctl: 3.1.0

Built with OpenMP: True

threadpoolctl info:
       user_api: openmp
   internal_api: openmp
         prefix: vcomp
       filepath: C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None
    num_threads: 8

       user_api: blas
   internal_api: openblas
         prefix: libopenblas
       filepath: C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
        version: 0.3.21
threading_layer: pthreads
   architecture: Haswell
    num_threads: 8

       user_api: blas
   internal_api: openblas
         prefix: libopenblas
       filepath: C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy.libs\libopenblas-802f9ed1179cb9c9b03d67ff79f48187.dll
        version: 0.3.18
threading_layer: pthreads
   architecture: Haswell
    num_threads: 8
>>> import sksurv; print("sksurv:", sksurv.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sksurv'
>>> import cvxopt; print("cvxopt:", cvxopt.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cvxopt'
>>> import cvxpy; print("cvxpy:", cvxpy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cvxpy'
>>> import numexpr; print("numexpr:", numexpr.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numexpr'
>>> import osqp; print("osqp:", osqp.OSQP().version())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'osqp'
```

**Comment by sebp** [comment]
Python 3.11 is not supported yet
