### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by talatccan** [sebp/scikit-survival#37]
I tried to install it but i get this error: (Im using windows and python 3.6-x64)

```
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "sksurv.bintrees._binarytrees" sources
building extension "sksurv.ensemble._coxph_loss" sources
building extension "sksurv.kernels._clinical_kernel" sources
building extension "sksurv.linear_model._coxnet" sources
building extension "sksurv.svm._prsvm" sources
building extension "sksurv.svm._minlip" sources
building data_files sources
build_src: building npy-pkg config files
writing scikit_survival.egg-info\PKG-INFO
writing dependency_links to scikit_survival.egg-info\dependency_links.txt
writing requirements to scikit_survival.egg-info\requires.txt
writing top-level names to scikit_survival.egg-info\top_level.txt
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.py' under directory 'examples'
warning: no files found matching '*.pxd' under directory 'sksurv'
warning: no directories found matching 'sksurv\linear_model\src\eigen\Eigen'
no previously-included directories found matching 'doc\_build'
no previously-included directories found matching 'doc\generated'
no previously-included directories found matching '*\__pycache__'
no previously-included directories found matching '*\.ipynb_checkpoints'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
writing manifest file 'scikit_survival.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
building 'sksurv.ensemble._coxph_loss' extension
compiling C sources
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\talat\PycharmP
rojects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\core\include -IC:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\cor
e\include -IC:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\include -IC:\Users\talat\AppData\Local\Programs\Python\Python36\include -IC:\Users\talat\AppData
\Local\Programs\Python\Python36\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" -I"C:\Program Files (x86)\Window
s Kits\10\include\10.0.17134.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um
" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsksurv\ensemble\_coxph_lo
ss.c /Fobuild\temp.win-amd64-3.6\Release\sksurv\ensemble\_coxph_loss.obj
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    setup_package()
  File "setup.py", line 90, in setup_package
    setup(**metadata)
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\setuptools-39.1.0-py3.6.egg\setuptools\__init__.py", line 129, in setup
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\command\install.py", line 62, in run
    r = self.setuptools_run()
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\command\install.py", line 56, in setuptools_run
    self.do_egg_install()
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\setuptools-39.1.0-py3.6.egg\setuptools\command\install.py", line 109, in do_egg_in
stall
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\setuptools-39.1.0-py3.6.egg\setuptools\command\bdist_egg.py", line 172, in run
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\setuptools-39.1.0-py3.6.egg\setuptools\command\bdist_egg.py", line 158, in call_co
mmand
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\setuptools-39.1.0-py3.6.egg\setuptools\command\install_lib.py", line 11, in run
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\command\build_ext.py", line 262, in run
    self.build_extensions()
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\command\build_ext.py", line 370, in build_extension
    **kws)
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\_msvccompiler.py", line 423, in compile
    self.spawn(args)
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\distutils\_msvccompiler.py", line 542, in spawn
    return super().spawn(cmd)
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\ccompiler.py", line 89, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\ccompiler.py", line 139, in CCompiler_spawn
    s, o = exec_command(cmd)
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\exec_command.py", line 213, in exec_command
    **env)
  File "C:\Users\talat\PycharmProjects\SurvivalAnalysis_Lifetime_Example\lib\site-packages\numpy\distutils\exec_command.py", line 256, in _exec_command
    text, err = proc.communicate()
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
  File "C:\Users\talat\AppData\Local\Programs\Python\Python36\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 322: character maps to <undefined>

```

**Comment by sebp** [comment]
I highly recommend to use the pre-built 
[anaconda](https://www.anaconda.com/) package, which you can install by 
running

conda install -c sebp scikit-survival

**Comment by aspds18** [comment]
Hi,
I installed Anaconda, version 2020.02 and then try to install the package. It took a lot of time, failed  and gave messages of conflict with a lot of other packages. I attached a picture of the last few ones.
![survival_conflicts](https://user-images.githubusercontent.com/43660781/79058117-68f57000-7c1e-11ea-8abf-0e169683bf7b.JPG)

**Comment by sebp** [comment]
Can you please try with the latest version 0.12.0?

**Comment by aspds18** [comment]
Hi, thanks for the reply. I was able to install it in a separate environment. The first time I tried in the anaconda base environment and it didn't work. Thanks!
